# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae10c210d1157d83fdd36cac1432331bc4fd28d3e8ec47357e023d8faecd9f4fcbf93d118c105a45136b8ee3ff204715767137dbddbd2f2a75df0b0e3f7418a8

test:
  secret_key_base: fb608ff330127d597f7f54509f37520435e505beb1d1308862bac046fc30b9caafac60266da238c8a48d34aa4001c6cb2ec088251cb7dedd641a4c1fa7273002

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
